### ISSUE TITLE
User Journey #1

### ISSUE THREAD

**Issue by yasminhillis** [facg3/Khobza#1]
As a user I want to browse all the sandwiches available in the cafeteria and view details about each sandwich 
there so that I can order my sandwiches without getting distracted from my work 

Acceptance Criteria
- [ ] Sign up #2
- [ ] Log in #3
- [ ] Homepage #4
- [ ]  Ordering #5
- [ ] View my cart #6
- [ ] Confirming the order #7
- [ ] Notifications #8
- [ ] View nearby restaurants through the map #9
- [ ] Suggestions #10
- [ ] Log Out #11
